### ISSUE TITLE
Cargar métodos anteriores

### ISSUE THREAD

**Issue by joseetmanuel** [joseetmanuel/ModuloSeguridad2#3]
- [x] Se debe en este issue poner la fecha (aproximada) de liberación de cada método

Los métodos que deben funcionar al 100% son:
- [x] login
- [x] valida
- [x] ValToken
- [x] RestorePass, (debe recuperar el pass de firebae)
- [x] GetAllUsers/:idApp

Estos deben estar:
- [x] Documentados en la wiki de github
- [x] Documentación en el código de acuerdo a los estándares de Andrade (http://189.204.141.199:8080/mediawiki/index.php/Documentaci%C3%B3n_C%C3%B3digo_Fuente)

**Comment by MartinPacheco** [comment]
done.
